import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { backendEnvironment } from '../runtime-env.mjs';
import { needsSecretsKey } from '../key-store.mjs';
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sparkdash-sudo-storage-'));
Object.assign(process.env, backendEnvironment({ dataDir: dir, token: '1'.repeat(64), secretsKey: '2'.repeat(64) }));
const { SparkRegistry } = await import('../../server/sparks/SparkRegistry.js');
const { loadSecrets } = await import('../../server/secretsStore.js');
test.after(() => fs.rmSync(dir, { recursive: true, force: true }));
test('sudo secrets remain separate, encrypted, survive SSH edits and restart, and are deleted with the device', () => {
  const registry = new SparkRegistry();
  registry.addSpark({ id: 'fixture', name: 'Fixture', lanIp: '127.0.0.1', ssh: { host: '127.0.0.1' } });
  registry.setSudoPassword('fixture', 'sudo-secret');
  registry.setPassword('fixture', 'ssh-secret');
  const raw = fs.readFileSync(path.join(dir, 'sparks-secrets.json'), 'utf8');
  assert.equal(raw.includes('sudo-secret'), false);
  assert.equal(raw.includes('ssh-secret'), false);
  assert.equal(JSON.stringify(registry.publicSparks).includes('sudo-secret'), false);
  assert.equal(JSON.stringify(registry.getSpark('fixture')).includes('sudo-secret'), false);
  assert.equal(fs.readFileSync(path.join(dir, 'sparks.json'), 'utf8').includes('sudo-secret'), false);
  assert.equal(needsSecretsKey(dir), true);
  const restarted = new SparkRegistry();
  assert.equal(restarted.getSudoPassword('fixture'), 'sudo-secret');
  assert.equal(restarted.getSpark('fixture').ssh.password, 'ssh-secret');
  restarted.updateSpark('fixture', { ssh: { host: 'other-host' } });
  assert.equal(restarted.getSudoPassword('fixture'), undefined, 'saved sudo secret must not follow a changed SSH destination');
  assert.equal(loadSecrets().sudoPasswords.size, 0, 'changing the target removes the stale secret from disk');
  restarted.updateSpark('fixture', { ssh: { host: '127.0.0.1' } });
  assert.equal(restarted.getSudoPassword('fixture'), undefined, 'switching back cannot resurrect an old credential');
  const verifiedSpark = restarted.getSpark('fixture');
  restarted.updateSpark('fixture', { ssh: { user: 'different-account' } });
  assert.throws(() => restarted.setSudoPassword('fixture', 'old-target-secret', verifiedSpark), /target changed/);
  assert.equal(loadSecrets().sudoPasswords.size, 0);
  restarted.setSudoPassword('fixture', null);
  assert.equal(loadSecrets().sudoPasswords.size, 0);
  assert.equal(loadSecrets().passwords.get('fixture'), 'ssh-secret');
  restarted.setSudoPassword('fixture', 'sudo-secret');
  restarted.removeSpark('fixture');
  assert.equal(loadSecrets().sudoPasswords.size, 0);
});
